site_name: Blog
site_url: https://jhqiu21.github.io/blog
repo_name: jhqiu21/Blog
repo_url: https://github.com/jhqiu21/Blog
theme: 
  name: material
  plugins:
  - blog
  - tags
  palette:
    #- media: "(prefers-color-scheme: light)" # color scheme: light
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    #- media: "(prefers-color-scheme: dark)" # color scheme: dark
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: octicons/sun-16
        name: Switch to system preference
  language: en
  icon:
    logo: material/earth
    repo: fontawesome/brands/git-alt
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - content.tabs.link
    - navigation.indexes 
    - navigation.footer # Add prev and next link in the footer
    - navigation.tabs
    - toc.follow
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets    
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a herf="https://jhqiu21.github.io/Blog/" target="_blank">Jin Hang's Tech Blog</a>

extra: 
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/jhqiu21
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jinhang-qiu-417509288/
    

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css   
  - css/custom.css


nav:
  - Hello: index.md 
  - Project:
    - Project/index.md
    - Project/Gitlet.md
  - Blog:
    - Blog/index.md
    - 2024:
      - Blog/2024/Page.md

